// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    goals,
    subjects,
    tasks,
    settings,
  ];
  late final Shape0 goals = Shape0(
    source: i0.VersionedTable(
      entityName: 'goals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 subjects = Shape1(
    source: i0.VersionedTable(
      entityName: 'subjects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 tasks = Shape2(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_5,
        _column_11,
        _column_6,
        _column_7,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 settings = Shape3(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_18, _column_19, _column_20, _column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deadlineDate =>
      columnsByName['deadline_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'deadline_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'active\'',
      defaultValue: const i1.CustomExpression('\'active\''),
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get goalId =>
      columnsByName['goal_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get color =>
      columnsByName['color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'goal_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES goals(id)',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'color',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get goalId =>
      columnsByName['goal_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get subjectId =>
      columnsByName['subject_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get plannedDate =>
      columnsByName['planned_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get estimatedMinutes =>
      columnsByName['estimated_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get originalPlannedDate =>
      columnsByName['original_planned_date']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'subject_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES subjects(id)',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'planned_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'estimated_minutes',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'todo\'',
      defaultValue: const i1.CustomExpression('\'todo\''),
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'original_planned_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dailyAvailableMinutes =>
      columnsByName['daily_available_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get availableWeekdays =>
      columnsByName['available_weekdays']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'daily_available_minutes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 120',
      defaultValue: const i1.CustomExpression('120'),
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'available_weekdays',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'1,2,3,4,5,6,7\'',
      defaultValue: const i1.CustomExpression('\'1,2,3,4,5,6,7\''),
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    goals,
    subjects,
    tasks,
    settings,
  ];
  late final Shape0 goals = Shape0(
    source: i0.VersionedTable(
      entityName: 'goals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 subjects = Shape1(
    source: i0.VersionedTable(
      entityName: 'subjects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 tasks = Shape4(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_5,
        _column_11,
        _column_6,
        _column_7,
        _column_17,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 settings = Shape3(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_18, _column_19, _column_20, _column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get goalId =>
      columnsByName['goal_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get subjectId =>
      columnsByName['subject_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get plannedDate =>
      columnsByName['planned_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get estimatedMinutes =>
      columnsByName['estimated_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get originalPlannedDate =>
      columnsByName['original_planned_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'archived_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    goals,
    subjects,
    recurrenceTemplates,
    tasks,
    settings,
  ];
  late final Shape0 goals = Shape0(
    source: i0.VersionedTable(
      entityName: 'goals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 subjects = Shape1(
    source: i0.VersionedTable(
      entityName: 'subjects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 recurrenceTemplates = Shape5(
    source: i0.VersionedTable(
      entityName: 'recurrence_templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_15,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tasks = Shape6(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_5,
        _column_11,
        _column_6,
        _column_7,
        _column_17,
        _column_21,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 settings = Shape3(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_18, _column_19, _column_20, _column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get goalId =>
      columnsByName['goal_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get subjectId =>
      columnsByName['subject_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get estimatedMinutes =>
      columnsByName['estimated_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get ruleType =>
      columnsByName['rule_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ruleJson =>
      columnsByName['rule_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startDate =>
      columnsByName['start_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get endDate =>
      columnsByName['end_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get active =>
      columnsByName['active']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get generatedThroughDate =>
      columnsByName['generated_through_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'rule_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'rule_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'start_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'end_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'active',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (active IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'generated_through_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get goalId =>
      columnsByName['goal_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get subjectId =>
      columnsByName['subject_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get plannedDate =>
      columnsByName['planned_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get estimatedMinutes =>
      columnsByName['estimated_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get originalPlannedDate =>
      columnsByName['original_planned_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get recurrenceTemplateId =>
      columnsByName['recurrence_template_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'recurrence_template_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES recurrence_templates(id)',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    goals,
    subjects,
    recurrenceTemplates,
    tasks,
    settings,
  ];
  late final Shape0 goals = Shape0(
    source: i0.VersionedTable(
      entityName: 'goals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 subjects = Shape1(
    source: i0.VersionedTable(
      entityName: 'subjects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 recurrenceTemplates = Shape7(
    source: i0.VersionedTable(
      entityName: 'recurrence_templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_15,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_6,
        _column_7,
        _column_29,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tasks = Shape6(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_5,
        _column_11,
        _column_6,
        _column_7,
        _column_17,
        _column_21,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 settings = Shape3(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_18, _column_19, _column_20, _column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get goalId =>
      columnsByName['goal_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get subjectId =>
      columnsByName['subject_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get estimatedMinutes =>
      columnsByName['estimated_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get ruleType =>
      columnsByName['rule_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ruleJson =>
      columnsByName['rule_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startDate =>
      columnsByName['start_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get endDate =>
      columnsByName['end_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get active =>
      columnsByName['active']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get generatedThroughDate =>
      columnsByName['generated_through_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get deletedInstanceDates =>
      columnsByName['deleted_instance_dates']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'deleted_instance_dates',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    goals,
    subjects,
    recurrenceTemplates,
    tasks,
    settings,
  ];
  late final Shape0 goals = Shape0(
    source: i0.VersionedTable(
      entityName: 'goals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 subjects = Shape1(
    source: i0.VersionedTable(
      entityName: 'subjects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 recurrenceTemplates = Shape7(
    source: i0.VersionedTable(
      entityName: 'recurrence_templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_15,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_6,
        _column_7,
        _column_29,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tasks = Shape6(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_5,
        _column_11,
        _column_6,
        _column_7,
        _column_17,
        _column_21,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 settings = Shape8(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_30,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dailyAvailableMinutes =>
      columnsByName['daily_available_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get availableWeekdays =>
      columnsByName['available_weekdays']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get closeBehavior =>
      columnsByName['close_behavior']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'close_behavior',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'exit\'',
      defaultValue: const i1.CustomExpression('\'exit\''),
    );

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    goals,
    subjects,
    milestones,
    recurrenceTemplates,
    tasks,
    settings,
  ];
  late final Shape0 goals = Shape0(
    source: i0.VersionedTable(
      entityName: 'goals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 subjects = Shape1(
    source: i0.VersionedTable(
      entityName: 'subjects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 milestones = Shape9(
    source: i0.VersionedTable(
      entityName: 'milestones',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_1,
        _column_31,
        _column_16,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 recurrenceTemplates = Shape7(
    source: i0.VersionedTable(
      entityName: 'recurrence_templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_15,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_6,
        _column_7,
        _column_29,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tasks = Shape6(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_5,
        _column_11,
        _column_6,
        _column_7,
        _column_17,
        _column_21,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 settings = Shape8(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_30,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get goalId =>
      columnsByName['goal_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema8 extends i0.VersionedSchema {
  Schema8({required super.database}) : super(version: 8);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    goals,
    subjects,
    milestones,
    recurrenceTemplates,
    tasks,
    settings,
    checklistItems,
  ];
  late final Shape0 goals = Shape0(
    source: i0.VersionedTable(
      entityName: 'goals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 subjects = Shape1(
    source: i0.VersionedTable(
      entityName: 'subjects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 milestones = Shape9(
    source: i0.VersionedTable(
      entityName: 'milestones',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_1,
        _column_31,
        _column_16,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 recurrenceTemplates = Shape7(
    source: i0.VersionedTable(
      entityName: 'recurrence_templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_15,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_6,
        _column_7,
        _column_29,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tasks = Shape6(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_5,
        _column_11,
        _column_6,
        _column_7,
        _column_17,
        _column_21,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 settings = Shape8(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_30,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 checklistItems = Shape10(
    source: i0.VersionedTable(
      entityName: 'checklist_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_32,
        _column_1,
        _column_33,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get taskId =>
      columnsByName['task_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get done =>
      columnsByName['done']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'task_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES tasks(id)',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'done',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (done IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

final class Schema9 extends i0.VersionedSchema {
  Schema9({required super.database}) : super(version: 9);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    goals,
    subjects,
    milestones,
    recurrenceTemplates,
    tasks,
    settings,
    checklistItems,
  ];
  late final Shape0 goals = Shape0(
    source: i0.VersionedTable(
      entityName: 'goals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 subjects = Shape1(
    source: i0.VersionedTable(
      entityName: 'subjects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 milestones = Shape9(
    source: i0.VersionedTable(
      entityName: 'milestones',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_1,
        _column_31,
        _column_16,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 recurrenceTemplates = Shape7(
    source: i0.VersionedTable(
      entityName: 'recurrence_templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_15,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_6,
        _column_7,
        _column_29,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tasks = Shape6(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_5,
        _column_11,
        _column_6,
        _column_7,
        _column_17,
        _column_21,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 settings = Shape11(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_30,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 checklistItems = Shape10(
    source: i0.VersionedTable(
      entityName: 'checklist_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_32,
        _column_1,
        _column_33,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dailyAvailableMinutes =>
      columnsByName['daily_available_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get availableWeekdays =>
      columnsByName['available_weekdays']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get closeBehavior =>
      columnsByName['close_behavior']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get autoBackupEnabled =>
      columnsByName['auto_backup_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get localBackupFolder =>
      columnsByName['local_backup_folder']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get webdavUrl =>
      columnsByName['webdav_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get webdavUsername =>
      columnsByName['webdav_username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get webdavPasswordSaved =>
      columnsByName['webdav_password_saved']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastAutoBackupAt =>
      columnsByName['last_auto_backup_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'auto_backup_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (auto_backup_enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'local_backup_folder',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'webdav_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'webdav_username',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'webdav_password_saved',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (webdav_password_saved IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_auto_backup_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

final class Schema10 extends i0.VersionedSchema {
  Schema10({required super.database}) : super(version: 10);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    goals,
    subjects,
    milestones,
    recurrenceTemplates,
    tasks,
    settings,
    checklistItems,
    subjectsGoalIdx,
    milestonesGoalIdx,
    tasksGoalArchivedIdx,
    tasksPlannedDateIdx,
    tasksStatusArchivedIdx,
    tasksStatusCompletedIdx,
    recurrenceTemplatesGoalIdx,
    checklistItemsTaskIdx,
  ];
  late final Shape0 goals = Shape0(
    source: i0.VersionedTable(
      entityName: 'goals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 subjects = Shape1(
    source: i0.VersionedTable(
      entityName: 'subjects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 milestones = Shape9(
    source: i0.VersionedTable(
      entityName: 'milestones',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_1,
        _column_31,
        _column_16,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 recurrenceTemplates = Shape7(
    source: i0.VersionedTable(
      entityName: 'recurrence_templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_15,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_6,
        _column_7,
        _column_29,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tasks = Shape6(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_5,
        _column_11,
        _column_6,
        _column_7,
        _column_17,
        _column_21,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 settings = Shape11(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_30,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 checklistItems = Shape10(
    source: i0.VersionedTable(
      entityName: 'checklist_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_32,
        _column_1,
        _column_33,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index subjectsGoalIdx = i1.Index(
    'subjects_goal_idx',
    'CREATE INDEX subjects_goal_idx ON subjects (goal_id)',
  );
  final i1.Index milestonesGoalIdx = i1.Index(
    'milestones_goal_idx',
    'CREATE INDEX milestones_goal_idx ON milestones (goal_id)',
  );
  final i1.Index tasksGoalArchivedIdx = i1.Index(
    'tasks_goal_archived_idx',
    'CREATE INDEX tasks_goal_archived_idx ON tasks (goal_id, archived_at)',
  );
  final i1.Index tasksPlannedDateIdx = i1.Index(
    'tasks_planned_date_idx',
    'CREATE INDEX tasks_planned_date_idx ON tasks (planned_date)',
  );
  final i1.Index tasksStatusArchivedIdx = i1.Index(
    'tasks_status_archived_idx',
    'CREATE INDEX tasks_status_archived_idx ON tasks (status, archived_at)',
  );
  final i1.Index tasksStatusCompletedIdx = i1.Index(
    'tasks_status_completed_idx',
    'CREATE INDEX tasks_status_completed_idx ON tasks (status, completed_at)',
  );
  final i1.Index recurrenceTemplatesGoalIdx = i1.Index(
    'recurrence_templates_goal_idx',
    'CREATE INDEX recurrence_templates_goal_idx ON recurrence_templates (goal_id)',
  );
  final i1.Index checklistItemsTaskIdx = i1.Index(
    'checklist_items_task_idx',
    'CREATE INDEX checklist_items_task_idx ON checklist_items (task_id)',
  );
}

final class Schema11 extends i0.VersionedSchema {
  Schema11({required super.database}) : super(version: 11);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    goals,
    subjects,
    milestones,
    recurrenceTemplates,
    tasks,
    settings,
    checklistItems,
    subjectsGoalIdx,
    milestonesGoalIdx,
    tasksGoalArchivedIdx,
    tasksPlannedDateIdx,
    tasksStatusArchivedIdx,
    tasksStatusCompletedIdx,
    recurrenceTemplatesGoalIdx,
    checklistItemsTaskIdx,
  ];
  late final Shape0 goals = Shape0(
    source: i0.VersionedTable(
      entityName: 'goals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 subjects = Shape1(
    source: i0.VersionedTable(
      entityName: 'subjects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 milestones = Shape9(
    source: i0.VersionedTable(
      entityName: 'milestones',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_1,
        _column_31,
        _column_16,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 recurrenceTemplates = Shape7(
    source: i0.VersionedTable(
      entityName: 'recurrence_templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_15,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_6,
        _column_7,
        _column_29,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tasks = Shape6(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_5,
        _column_11,
        _column_6,
        _column_7,
        _column_17,
        _column_21,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 settings = Shape12(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_30,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 checklistItems = Shape10(
    source: i0.VersionedTable(
      entityName: 'checklist_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_32,
        _column_1,
        _column_33,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index subjectsGoalIdx = i1.Index(
    'subjects_goal_idx',
    'CREATE INDEX subjects_goal_idx ON subjects (goal_id)',
  );
  final i1.Index milestonesGoalIdx = i1.Index(
    'milestones_goal_idx',
    'CREATE INDEX milestones_goal_idx ON milestones (goal_id)',
  );
  final i1.Index tasksGoalArchivedIdx = i1.Index(
    'tasks_goal_archived_idx',
    'CREATE INDEX tasks_goal_archived_idx ON tasks (goal_id, archived_at)',
  );
  final i1.Index tasksPlannedDateIdx = i1.Index(
    'tasks_planned_date_idx',
    'CREATE INDEX tasks_planned_date_idx ON tasks (planned_date)',
  );
  final i1.Index tasksStatusArchivedIdx = i1.Index(
    'tasks_status_archived_idx',
    'CREATE INDEX tasks_status_archived_idx ON tasks (status, archived_at)',
  );
  final i1.Index tasksStatusCompletedIdx = i1.Index(
    'tasks_status_completed_idx',
    'CREATE INDEX tasks_status_completed_idx ON tasks (status, completed_at)',
  );
  final i1.Index recurrenceTemplatesGoalIdx = i1.Index(
    'recurrence_templates_goal_idx',
    'CREATE INDEX recurrence_templates_goal_idx ON recurrence_templates (goal_id)',
  );
  final i1.Index checklistItemsTaskIdx = i1.Index(
    'checklist_items_task_idx',
    'CREATE INDEX checklist_items_task_idx ON checklist_items (task_id)',
  );
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dailyAvailableMinutes =>
      columnsByName['daily_available_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get availableWeekdays =>
      columnsByName['available_weekdays']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get closeBehavior =>
      columnsByName['close_behavior']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get autoBackupEnabled =>
      columnsByName['auto_backup_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get localBackupFolder =>
      columnsByName['local_backup_folder']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get webdavUrl =>
      columnsByName['webdav_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get webdavUsername =>
      columnsByName['webdav_username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get webdavPasswordSaved =>
      columnsByName['webdav_password_saved']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastAutoBackupAt =>
      columnsByName['last_auto_backup_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get webdavSyncEnabled =>
      columnsByName['webdav_sync_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastPushedSeq =>
      columnsByName['last_pushed_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'webdav_sync_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (webdav_sync_enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_pushed_seq',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_synced_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

final class Schema12 extends i0.VersionedSchema {
  Schema12({required super.database}) : super(version: 12);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    goals,
    subjects,
    milestones,
    recurrenceTemplates,
    tasks,
    settings,
    checklistItems,
    subjectsGoalIdx,
    milestonesGoalIdx,
    tasksGoalArchivedIdx,
    tasksPlannedDateIdx,
    tasksStatusArchivedIdx,
    tasksStatusCompletedIdx,
    recurrenceTemplatesGoalIdx,
    checklistItemsTaskIdx,
  ];
  late final Shape0 goals = Shape0(
    source: i0.VersionedTable(
      entityName: 'goals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 subjects = Shape1(
    source: i0.VersionedTable(
      entityName: 'subjects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 milestones = Shape9(
    source: i0.VersionedTable(
      entityName: 'milestones',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_1,
        _column_31,
        _column_16,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 recurrenceTemplates = Shape7(
    source: i0.VersionedTable(
      entityName: 'recurrence_templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_15,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_6,
        _column_7,
        _column_29,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tasks = Shape6(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_5,
        _column_11,
        _column_6,
        _column_7,
        _column_17,
        _column_21,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 settings = Shape13(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_30,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 checklistItems = Shape10(
    source: i0.VersionedTable(
      entityName: 'checklist_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_32,
        _column_1,
        _column_33,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index subjectsGoalIdx = i1.Index(
    'subjects_goal_idx',
    'CREATE INDEX subjects_goal_idx ON subjects (goal_id)',
  );
  final i1.Index milestonesGoalIdx = i1.Index(
    'milestones_goal_idx',
    'CREATE INDEX milestones_goal_idx ON milestones (goal_id)',
  );
  final i1.Index tasksGoalArchivedIdx = i1.Index(
    'tasks_goal_archived_idx',
    'CREATE INDEX tasks_goal_archived_idx ON tasks (goal_id, archived_at)',
  );
  final i1.Index tasksPlannedDateIdx = i1.Index(
    'tasks_planned_date_idx',
    'CREATE INDEX tasks_planned_date_idx ON tasks (planned_date)',
  );
  final i1.Index tasksStatusArchivedIdx = i1.Index(
    'tasks_status_archived_idx',
    'CREATE INDEX tasks_status_archived_idx ON tasks (status, archived_at)',
  );
  final i1.Index tasksStatusCompletedIdx = i1.Index(
    'tasks_status_completed_idx',
    'CREATE INDEX tasks_status_completed_idx ON tasks (status, completed_at)',
  );
  final i1.Index recurrenceTemplatesGoalIdx = i1.Index(
    'recurrence_templates_goal_idx',
    'CREATE INDEX recurrence_templates_goal_idx ON recurrence_templates (goal_id)',
  );
  final i1.Index checklistItemsTaskIdx = i1.Index(
    'checklist_items_task_idx',
    'CREATE INDEX checklist_items_task_idx ON checklist_items (task_id)',
  );
}

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dailyAvailableMinutes =>
      columnsByName['daily_available_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get availableWeekdays =>
      columnsByName['available_weekdays']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get closeBehavior =>
      columnsByName['close_behavior']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get autoBackupEnabled =>
      columnsByName['auto_backup_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get localBackupFolder =>
      columnsByName['local_backup_folder']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get webdavUrl =>
      columnsByName['webdav_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get webdavUsername =>
      columnsByName['webdav_username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get webdavPasswordSaved =>
      columnsByName['webdav_password_saved']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastAutoBackupAt =>
      columnsByName['last_auto_backup_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get webdavSyncEnabled =>
      columnsByName['webdav_sync_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastPushedSeq =>
      columnsByName['last_pushed_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get themeMode =>
      columnsByName['theme_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'theme_mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'system\'',
      defaultValue: const i1.CustomExpression('\'system\''),
    );

final class Schema13 extends i0.VersionedSchema {
  Schema13({required super.database}) : super(version: 13);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    goals,
    subjects,
    milestones,
    recurrenceTemplates,
    tasks,
    settings,
    checklistItems,
    subjectsGoalIdx,
    milestonesGoalIdx,
    tasksGoalArchivedIdx,
    tasksPlannedDateIdx,
    tasksStatusArchivedIdx,
    tasksStatusCompletedIdx,
    recurrenceTemplatesGoalIdx,
    checklistItemsTaskIdx,
  ];
  late final Shape0 goals = Shape0(
    source: i0.VersionedTable(
      entityName: 'goals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 subjects = Shape1(
    source: i0.VersionedTable(
      entityName: 'subjects',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 milestones = Shape9(
    source: i0.VersionedTable(
      entityName: 'milestones',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_1,
        _column_31,
        _column_16,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 recurrenceTemplates = Shape7(
    source: i0.VersionedTable(
      entityName: 'recurrence_templates',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_15,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_6,
        _column_7,
        _column_29,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 tasks = Shape6(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_8,
        _column_12,
        _column_1,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_5,
        _column_11,
        _column_6,
        _column_7,
        _column_17,
        _column_21,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 settings = Shape14(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_30,
        _column_34,
        _column_35,
        _column_39,
        _column_43,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 checklistItems = Shape10(
    source: i0.VersionedTable(
      entityName: 'checklist_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_32,
        _column_1,
        _column_33,
        _column_11,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index subjectsGoalIdx = i1.Index(
    'subjects_goal_idx',
    'CREATE INDEX subjects_goal_idx ON subjects (goal_id)',
  );
  final i1.Index milestonesGoalIdx = i1.Index(
    'milestones_goal_idx',
    'CREATE INDEX milestones_goal_idx ON milestones (goal_id)',
  );
  final i1.Index tasksGoalArchivedIdx = i1.Index(
    'tasks_goal_archived_idx',
    'CREATE INDEX tasks_goal_archived_idx ON tasks (goal_id, archived_at)',
  );
  final i1.Index tasksPlannedDateIdx = i1.Index(
    'tasks_planned_date_idx',
    'CREATE INDEX tasks_planned_date_idx ON tasks (planned_date)',
  );
  final i1.Index tasksStatusArchivedIdx = i1.Index(
    'tasks_status_archived_idx',
    'CREATE INDEX tasks_status_archived_idx ON tasks (status, archived_at)',
  );
  final i1.Index tasksStatusCompletedIdx = i1.Index(
    'tasks_status_completed_idx',
    'CREATE INDEX tasks_status_completed_idx ON tasks (status, completed_at)',
  );
  final i1.Index recurrenceTemplatesGoalIdx = i1.Index(
    'recurrence_templates_goal_idx',
    'CREATE INDEX recurrence_templates_goal_idx ON recurrence_templates (goal_id)',
  );
  final i1.Index checklistItemsTaskIdx = i1.Index(
    'checklist_items_task_idx',
    'CREATE INDEX checklist_items_task_idx ON checklist_items (task_id)',
  );
}

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dailyAvailableMinutes =>
      columnsByName['daily_available_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get availableWeekdays =>
      columnsByName['available_weekdays']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get closeBehavior =>
      columnsByName['close_behavior']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get autoBackupEnabled =>
      columnsByName['auto_backup_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get localBackupFolder =>
      columnsByName['local_backup_folder']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastAutoBackupAt =>
      columnsByName['last_auto_backup_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get themeMode =>
      columnsByName['theme_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
  required Future<void> Function(i1.Migrator m, Schema9 schema) from8To9,
  required Future<void> Function(i1.Migrator m, Schema10 schema) from9To10,
  required Future<void> Function(i1.Migrator m, Schema11 schema) from10To11,
  required Future<void> Function(i1.Migrator m, Schema12 schema) from11To12,
  required Future<void> Function(i1.Migrator m, Schema13 schema) from12To13,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      case 7:
        final schema = Schema8(database: database);
        final migrator = i1.Migrator(database, schema);
        await from7To8(migrator, schema);
        return 8;
      case 8:
        final schema = Schema9(database: database);
        final migrator = i1.Migrator(database, schema);
        await from8To9(migrator, schema);
        return 9;
      case 9:
        final schema = Schema10(database: database);
        final migrator = i1.Migrator(database, schema);
        await from9To10(migrator, schema);
        return 10;
      case 10:
        final schema = Schema11(database: database);
        final migrator = i1.Migrator(database, schema);
        await from10To11(migrator, schema);
        return 11;
      case 11:
        final schema = Schema12(database: database);
        final migrator = i1.Migrator(database, schema);
        await from11To12(migrator, schema);
        return 12;
      case 12:
        final schema = Schema13(database: database);
        final migrator = i1.Migrator(database, schema);
        await from12To13(migrator, schema);
        return 13;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
  required Future<void> Function(i1.Migrator m, Schema9 schema) from8To9,
  required Future<void> Function(i1.Migrator m, Schema10 schema) from9To10,
  required Future<void> Function(i1.Migrator m, Schema11 schema) from10To11,
  required Future<void> Function(i1.Migrator m, Schema12 schema) from11To12,
  required Future<void> Function(i1.Migrator m, Schema13 schema) from12To13,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
    from6To7: from6To7,
    from7To8: from7To8,
    from8To9: from8To9,
    from9To10: from9To10,
    from10To11: from10To11,
    from11To12: from11To12,
    from12To13: from12To13,
  ),
);
